// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1UPGMeXXiW-PMyhdApkuApAW4lmE3yYg',
    appId: '1:601604995816:web:8dbefb3ef614cd9025675d',
    messagingSenderId: '601604995816',
    projectId: 'canvan-b01b1',
    authDomain: 'canvan-b01b1.firebaseapp.com',
    storageBucket: 'canvan-b01b1.firebasestorage.app',
    measurementId: 'G-D4Y0ZSRY8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4ZJ3vqnPpf-gAYg2uOo3-r6ISvTOBoc4',
    appId: '1:601604995816:android:539922263195607525675d',
    messagingSenderId: '601604995816',
    projectId: 'canvan-b01b1',
    storageBucket: 'canvan-b01b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv7TKPomlecViAD11kNafGS40ZfScG6ZQ',
    appId: '1:601604995816:ios:def23690c2dcf36f25675d',
    messagingSenderId: '601604995816',
    projectId: 'canvan-b01b1',
    storageBucket: 'canvan-b01b1.firebasestorage.app',
    iosBundleId: 'com.example.getx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv7TKPomlecViAD11kNafGS40ZfScG6ZQ',
    appId: '1:601604995816:ios:def23690c2dcf36f25675d',
    messagingSenderId: '601604995816',
    projectId: 'canvan-b01b1',
    storageBucket: 'canvan-b01b1.firebasestorage.app',
    iosBundleId: 'com.example.getx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1UPGMeXXiW-PMyhdApkuApAW4lmE3yYg',
    appId: '1:601604995816:web:7fc7dcb5eb83400125675d',
    messagingSenderId: '601604995816',
    projectId: 'canvan-b01b1',
    authDomain: 'canvan-b01b1.firebaseapp.com',
    storageBucket: 'canvan-b01b1.firebasestorage.app',
    measurementId: 'G-BY775NT5B6',
  );
}
