// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo8I243id0Lzy_Usb_7MzlkSi-X7KNmCA',
    appId: '1:207920446622:web:109d1a345a8f74ab9ecf8f',
    messagingSenderId: '207920446622',
    projectId: 'fluuterbase',
    authDomain: 'fluuterbase.firebaseapp.com',
    storageBucket: 'fluuterbase.firebasestorage.app',
    measurementId: 'G-C51TKPGJ34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtm5FERmWwqrAA3ZyhywKLz7UqJj8ljI4',
    appId: '1:207920446622:android:28159bec380767219ecf8f',
    messagingSenderId: '207920446622',
    projectId: 'fluuterbase',
    storageBucket: 'fluuterbase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkFyjMR_7oS85-ZYQICliztAqzjPjd6xY',
    appId: '1:207920446622:ios:e6d48cee6057b1919ecf8f',
    messagingSenderId: '207920446622',
    projectId: 'fluuterbase',
    storageBucket: 'fluuterbase.firebasestorage.app',
    iosBundleId: 'com.example.getx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkFyjMR_7oS85-ZYQICliztAqzjPjd6xY',
    appId: '1:207920446622:ios:e6d48cee6057b1919ecf8f',
    messagingSenderId: '207920446622',
    projectId: 'fluuterbase',
    storageBucket: 'fluuterbase.firebasestorage.app',
    iosBundleId: 'com.example.getx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo8I243id0Lzy_Usb_7MzlkSi-X7KNmCA',
    appId: '1:207920446622:web:dcd086c35eab91039ecf8f',
    messagingSenderId: '207920446622',
    projectId: 'fluuterbase',
    authDomain: 'fluuterbase.firebaseapp.com',
    storageBucket: 'fluuterbase.firebasestorage.app',
    measurementId: 'G-PQ7L3LVYYY',
  );
}
